name: Debug Build

on:
  workflow_dispatch: # Manual trigger only

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Elm and Tailwind
        run: |
          npm install -g elm
          npm install -D tailwindcss

      - name: Project Structure
        run: |
          echo "Current directory:"
          pwd
          echo "Repository content:"
          ls -la
          echo "Source directory:"
          ls -la src || echo "src directory not found"
          echo "Public directory (before build):"
          ls -la public || echo "public directory not found"

      - name: Create directories
        run: |
          mkdir -p public
          mkdir -p src/css

      - name: Verify Elm files
        run: |
          echo "Main.elm exists?"
          if [ -f "src/Main.elm" ]; then echo "YES"; else echo "NO"; fi
          echo "Content of src directory:"
          ls -la src/

      - name: Build Elm
        run: |
          elm make src/Main.elm --output=public/main.js || echo "Elm build failed"
          echo "Elm build result:"
          ls -la public/ || echo "public directory not found after Elm build"

      - name: Create Tailwind config
        run: echo 'module.exports = { content: ["./public/index.html", "./src/**/*.elm"], theme: { extend: {} }, plugins: [] }' > tailwind.config.js

      - name: Create CSS input
        run: echo '@tailwind base; @tailwind components; @tailwind utilities;' > src/css/input.css

      - name: Build Tailwind
        run: |
          npx tailwindcss -i ./src/css/input.css -o ./public/output.css --minify || echo "Tailwind build failed"
          echo "Tailwind build result:"
          ls -la public/

      - name: Create HTML
        run: |
          echo '<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elm with Everbush Theme - Debug</title>
    <link href="output.css" rel="stylesheet">
    <script src="main.js"></script>
  </head>
  <body>
    <div id="elm-app"></div>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        try {
          if (typeof Elm !== "undefined" && Elm.Main) {
            console.log("Elm found, initializing app");
            var app = Elm.Main.init({
              node: document.getElementById("elm-app")
            });
          } else {
            console.error("Elm not found or Elm.Main not available");
            document.getElementById("elm-app").innerHTML = "<div style=\"padding: 20px; color: red;\">Elm application failed to load</div>";
          }
        } catch (e) {
          console.error("Error initializing Elm app:", e);
          document.getElementById("elm-app").innerHTML = "<div style=\"padding: 20px; color: red;\">Error: " + e.message + "</div>";
        }
      });
    </script>
    <div style="padding: 20px; margin-top: 20px; border: 1px solid #ccc;">
      <h2>Debug Information</h2>
      <p>Page loaded at: <span id="timestamp"></span></p>
      <p>Elm loaded: <span id="elm-status">Checking...</span></p>
      <script>
        document.getElementById("timestamp").textContent = new Date().toISOString();
        setTimeout(function() {
          document.getElementById("elm-status").textContent =
            (typeof Elm !== "undefined") ? "Yes" : "No";
        }, 500);
      </script>
    </div>
  </body>
</html>' > public/index.html

      - name: Final directory structure
        run: |
          echo "Final public directory content:"
          ls -la public/
          echo "File sizes:"
          du -h public/*

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages-debug
          clean: true
