name: Deploy Jellyfin Web Elm

on:
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Elm
        run: npm install -g elm

      - name: Create directories
        run: mkdir -p public

      - name: Build Elm
        run: elm make src/Main.elm --output=public/main.js --optimize

      - name: Install and Build Tailwind CSS
        run: |
          # Install tailwindcss globally
          npm install -D tailwindcss postcss autoprefixer

          # Run tailwindcss with npx
          npx tailwindcss -i ./src/css/input.css -o ./public/output.css --minify

      - name: Add .nojekyll file
        run: touch public/.nojekyll

      - name: Final directory structure
        run: ls -la public/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
          clean: true
